# Generated by Django 5.2 on 2025-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the salesperson. Duplicates are allowed.', max_length=254, null=True),
        ),
    ]
