# Generated by Django 5.2 on 2025-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(help_text='CUSIP identifier for the bond', max_length=9, unique=True)),
                ('description', models.CharField(help_text='Descriptive name of the security', max_length=200)),
                ('issue_date', models.DateField(help_text='Date the security was issued')),
                ('maturity_date', models.DateField(help_text='Date when principal is repaid')),
                ('call_date', models.DateField(blank=True, help_text='First call date, if applicable', null=True)),
                ('coupon', models.DecimalField(decimal_places=3, help_text='Annual coupon rate (e.g. 0.025 for 2.5%)', max_digits=5)),
                ('wal', models.DecimalField(decimal_places=3, help_text='Weighted Average Life in years', max_digits=5)),
            ],
        ),
    ]
