# Generated by Django 5.2 on 2025-04-21 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of bond units held')),
                ('face_value', models.DecimalField(decimal_places=2, help_text='Par value per unit', max_digits=12)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.security')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.customer')),
                ('securities', models.ManyToManyField(related_name='portfolios', through='portfolio.CustomerHolding', to='portfolio.security')),
            ],
        ),
        migrations.AddField(
            model_name='customerholding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='customerholding',
            unique_together={('portfolio', 'security')},
        ),
    ]
