# Generated by Django 5.2 on 2025-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_salesperson_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='cpr',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Conditional Prepayment Rate (CPR) as a percentage (e.g., 6.5 for 6.5%). Optional.', max_digits=8, null=True),
        ),
    ]
