# Generated by Django 5.2 on 2025-04-21 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_customerholding_portfolio_customerholding_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerholding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='book_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='book_yield',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='coupon',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='original_face_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='settlement_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='ticket_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique ticket identifier', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='wal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='coupon',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='security',
            name='cusip',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='security',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='maturity_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='wal',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='face_value',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='quantity',
        ),
    ]
