# Generated by Django 5.2 on 2025-05-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_security_cpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerholding',
            name='intention_code',
            field=models.CharField(choices=[('A', 'Available for Sale'), ('H', 'Held to Maturity'), ('T', 'Held for Trading')], help_text="Holding intention code (from Excel 'lc_xf1_cd'). Required.", max_length=1),
        ),
    ]
