# Generated by Django 5.2 on 2025-04-21 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_customerholding_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerholding',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.customer'),
        ),
    ]
