# Generated by Django 5.2 on 2025-04-21 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_customerholding_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(help_text='Users associated with this customer', related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
