# Generated by Django 5.2 on 2025-04-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_customer_user_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='day_count',
            field=models.CharField(choices=[('30/360', '30/360'), ('ACT/360', 'Actual/360'), ('ACT/365', 'Actual/365')], default='30/360', help_text='Day-count convention', max_length=7),
        ),
        migrations.AddField(
            model_name='security',
            name='factor',
            field=models.DecimalField(decimal_places=8, default=1.0, help_text='Paydown factor (0–1)', max_digits=12),
        ),
        migrations.AddField(
            model_name='security',
            name='payment_frequency',
            field=models.IntegerField(choices=[(1, 'Annual'), (2, 'Semiannual'), (4, 'Quarterly'), (12, 'Monthly')], default=2, help_text='Coupon payments per year'),
        ),
    ]
