# Generated by Django 5.2 on 2025-04-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_security_day_count_security_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, help_text='External unique customer number from Excel', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerholding',
            name='customer_number',
            field=models.CharField(blank=True, help_text='External customer number for lookup', max_length=20, null=True),
        ),
    ]
