# Generated by Django 5.2 on 2025-04-26 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_customer_customer_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Users allowed to see this customer's data", related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
