# Generated by Django 5.2 on 2025-04-27 19:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_customer_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Indicates if this is the default 'Primary Holdings' portfolio for the owner."),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, help_text='External unique customer number (e.g., from Excel import)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier.', unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="System users allowed to view/manage this customer's data", related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='book_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Book value price of the holding', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='book_yield',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Book yield of the holding', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='call_date',
            field=models.DateField(blank=True, help_text='Call date at time of snapshot/copy', null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='coupon',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Coupon at time of snapshot/copy', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer associated with this holding (should match portfolio owner)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.customer'),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='customer_number',
            field=models.CharField(blank=True, help_text="External customer number (should match portfolio owner's number)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='description',
            field=models.CharField(blank=True, help_text='Description at time of snapshot/copy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='maturity_date',
            field=models.DateField(blank=True, help_text='Maturity date at time of snapshot/copy', null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='original_face_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original face value of the holding at purchase/acquisition', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='portfolio',
            field=models.ForeignKey(help_text='The portfolio this holding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='security',
            field=models.ForeignKey(help_text='The security being held', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.security'),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='settlement_date',
            field=models.DateField(blank=True, help_text='Date the holding settled', null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='settlement_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price at which the holding settled', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique internal identifier for this holding record', unique=True),
        ),
        migrations.AlterField(
            model_name='customerholding',
            name='wal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='WAL at time of snapshot/copy', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='User-defined name for the portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(help_text='The customer who owns this portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.customer'),
        ),
        migrations.AlterField(
            model_name='security',
            name='call_date',
            field=models.DateField(blank=True, help_text='Optional call date', null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='coupon',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Annual coupon rate (e.g., 5.125)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='cusip',
            field=models.CharField(help_text='Unique 9-character CUSIP identifier', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='day_count',
            field=models.CharField(choices=[('30/360', '30/360'), ('ACT/360', 'Actual/360'), ('ACT/365', 'Actual/365')], default='30/360', help_text='Day-count convention used for interest calculation', max_length=10),
        ),
        migrations.AlterField(
            model_name='security',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='security',
            name='factor',
            field=models.DecimalField(decimal_places=8, default=1.0, help_text='Current paydown factor (e.g., 1.0 for non-amortizing, <1 for amortizing)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='security',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='wal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weighted Average Life', max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='customerholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'security'), name='unique_security_per_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner', 'is_default'), name='unique_default_portfolio_per_owner'),
        ),
    ]
