# Generated by Django 5.2 on 2025-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_is_default_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesperson_email',
            field=models.EmailField(blank=True, help_text='Email address of the assigned salesperson for notifications.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesperson_name',
            field=models.CharField(blank=True, help_text='Name of the salesperson assigned to this customer.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='day_count',
            field=models.CharField(choices=[('30/360', '30/360'), ('ACT/360', 'Actual/360'), ('ACT/365', 'Actual/365')], default='30/360', help_text='Day-count convention', max_length=10),
        ),
        migrations.AlterField(
            model_name='security',
            name='factor',
            field=models.DecimalField(decimal_places=8, default=1.0, help_text='Current paydown factor', max_digits=12),
        ),
    ]
