# Generated by Django 5.2 on 2025-04-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_customer_salesperson_email_customer_salesperson_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(help_text='Unique 9-character CUSIP identifier for the offering.', max_length=9, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the offering available (e.g., par value).', max_digits=15, null=True)),
                ('description', models.CharField(blank=True, help_text='Description of the bond offering.', max_length=255)),
                ('coupon', models.DecimalField(blank=True, decimal_places=5, help_text='Annual coupon rate of the bond.', max_digits=8, null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='Maturity date of the bond.', null=True)),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=5, help_text='Yield of the offering.', max_digits=8, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, help_text='Price of the offering.', max_digits=12, null=True)),
                ('moody_rating', models.CharField(blank=True, help_text="Moody's credit rating.", max_length=10, null=True)),
                ('sp_rating', models.CharField(blank=True, help_text='S&P credit rating.', max_length=10, null=True)),
                ('call_date', models.DateField(blank=True, help_text='Optional call date for the bond.', null=True)),
                ('call_price', models.DecimalField(blank=True, decimal_places=6, help_text='Optional call price for the bond.', max_digits=12, null=True)),
                ('state', models.CharField(blank=True, help_text='State associated with the bond offering (e.g., issuer state).', max_length=2, null=True)),
                ('insurance', models.CharField(blank=True, help_text='Bond insurer, if any.', max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this offering record was last updated by the import.')),
            ],
            options={
                'verbose_name': 'Municipal Offering',
                'verbose_name_plural': 'Municipal Offerings',
                'ordering': ['maturity_date', 'cusip'],
            },
        ),
        migrations.AlterModelOptions(
            name='customerholding',
            options={'ordering': ['portfolio', 'security__cusip']},
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='customerholding',
            name='wal',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='securities',
        ),
    ]
